name: Build VST3 Only

on:
  workflow_dispatch:

jobs:
  build-windows-vst3:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          git submodule update --init --recursive
          git clone --depth 1 https://github.com/juce-framework/JUCE.git JUCE

      - name: Configure CMake
        run: |
          cmake -S . -B build -A x64 `
            -DZL_JUCE_FORMATS="VST3" `
            -DBUILD_INSTALLER=OFF `
            -DZL_BUILD_LINUX=OFF `
            -DZL_BUILD_MAC=OFF `
            -DZL_BUILD_WINDOWS=ON `
            -DNLopt_BUILD_JAVA=OFF `
            -DBUILD_TESTING=OFF

      - name: Build
        run: cmake --build build --config Release

      - name: Upload VST3
        uses: actions/upload-artifact@v4
        with:
          name: ZL_Equalizer_VST3
          path: build/Release/*.vst3
